// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: UserService.proto

package Models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserListService service

func NewUserListServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserListService service

type UserListService interface {
	GetUserList(ctx context.Context, in *UsersRequest, opts ...client.CallOption) (*UserListResponse, error)
}

type userListService struct {
	c    client.Client
	name string
}

func NewUserListService(name string, c client.Client) UserListService {
	return &userListService{
		c:    c,
		name: name,
	}
}

func (c *userListService) GetUserList(ctx context.Context, in *UsersRequest, opts ...client.CallOption) (*UserListResponse, error) {
	req := c.c.NewRequest(c.name, "UserListService.GetUserList", in)
	out := new(UserListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserListService service

type UserListServiceHandler interface {
	GetUserList(context.Context, *UsersRequest, *UserListResponse) error
}

func RegisterUserListServiceHandler(s server.Server, hdlr UserListServiceHandler, opts ...server.HandlerOption) error {
	type userListService interface {
		GetUserList(ctx context.Context, in *UsersRequest, out *UserListResponse) error
	}
	type UserListService struct {
		userListService
	}
	h := &userListServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserListService{h}, opts...))
}

type userListServiceHandler struct {
	UserListServiceHandler
}

func (h *userListServiceHandler) GetUserList(ctx context.Context, in *UsersRequest, out *UserListResponse) error {
	return h.UserListServiceHandler.GetUserList(ctx, in, out)
}
